services:
  beluga-demo-dev:
    build:
      context: ..
      dockerfile: docker/images/${ROSDISTRO:-humble}/Dockerfile
    image: ekumenlabs/beluga-demo-${ROSDISTRO:-humble}-dev
    hostname: beluga-demo-${ROSDISTRO:-humble}-dev
    container_name: beluga-demo-${ROSDISTRO:-humble}-dev
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    stdin_open: true
    tty: true
    user: ${USERID:-1000}:${GROUPID:-1000}
    #privileged: ${PRIVILEGED_CONTAINER:-false}
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
      - ..:/home/developer/ws/src/beluga_demo
      - beluga_demos_ccache:/home/developer/.ccache
      - /dev:/dev
  beluga-demo-dev-nvidia:
    extends:
      service: beluga-demo-dev
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  beluga_demos_ccache:
  gazebo_models:
  ignition_models:
